### ISSUE TITLE
Feat: Subcommand to manually submit a flag

### ISSUE THREAD

**Issue by felixalbrigtsen** [Cyberlandslaget/kriger#6]
To avoid typing out a lengthy curl with a bajillion options, something like `kriger flag ASDFG=` or `kriger submit ASDFG=` would help simplifying, as well as logging, manual flag submissions.

**Comment by 0xLE** [comment]
Resolved in https://github.com/Cyberlandslaget/kriger/commit/26c8ddc2144130c172cca4960f448f2113b71694
